### PR TITLE
Update sun-emitter.js

### PR DESCRIPTION
**Pull request by typh289**
added check if dateout is in the future, 
in my instance sun_nadir was being added with a past date and spamming in logs 
 macrozilla: starting dateout for sun_nadir with a wrong datetime (the previous day one)

### CODE REVIEW

**Comment by bewee** [comment]
Hi @typh289 

Looks pretty good. Why have you closed the issue🤔?

Regards :)

**Comment by typh289** [comment]
wrote it quickly and while logs now looks clear i didn't test if functionality is actually fine yet :)

**Comment by bewee** [comment]
Hi @typh289

no problem, just report back when it's all fine :)

Regards

**Review by bewee — APPROVED** [review]

**Comment by typh289** [comment]
Other triggers looks working fine but i don't see sun_nadir dateout being added at all now, previously it tried to add it thousands of times with a past date for 20 min or so until it got correctly but that made various logs files spammed full of "macrozilla: starting dateout for sun_nadir" daily, while for me it's now fine as i don't use that trigger it still need some work tho, i'll update when i get it good :D
i think it's related to this old suncalc issue
https://github.com/mourner/suncalc/issues/124

**Comment by bewee** [comment]
Hi @typh289

Sorry for replying that late. Somehow I didn't get notified for your answer🤔

I don't see any real use for this very specific sun trigger either tbh. So if you think it's ok I will just merge it as it is?

Regards

**Comment by typh289** [comment]
Well i think it's still better this way until the pull fixing that issue in suncalc directly get approved as before it made 5 full log files every night here trying to add that trigger :) looks like it's an issue only for those in some gmt + timezones due to how nadir is calculated, i guess who didn't see this issue before get nadir trigger in the future anyway so will still be working fine even with this

**Comment by bewee** [comment]
Hi @typh289

Thank you very much for the great contribution!
The new release is now available on the add-on list.

Regards :)

**Pull request merged**
